services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    restart: always

  tenc_db:
    restart: always
    image: postgres:17
    container_name: tenc_db
    environment:
      POSTGRES_DB: tenc
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./tenc_data:/var/lib/postgresql/data